export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const CHANGE_LAST_TIMESTAMP = "CHANGE_LAST_TIMESTAMP";
export const CHANGE_GAME_TYPE = "CHANGE_GAME_TYPE";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SEND_EMAIL = "SEND_EMAIL";

export const GET_BOARD_INFO = "GET_BOARD_INFO";
export const REMOVE_BOARD_INFO = "REMOVE_BOARD_INFO";
export const CHANGE_RESP_WORD = "CHANGE_RESP_WORD";
export const GET_REVEAL_WORD = "GET_REVEAL_WORD";
export const HINT_LOADING = "HINT_LOADING";
export const GET_REMOVE_TWO_KEYS = "GET_REMOVE_TWO_KEYS";
export const GET_SUM_TWO_LETTERS = "GET_SUM_TWO_LETTERS";
export const CHANE_SELECTED_KEY = "CHANE_SELECTED_KEY";
export const CHECK_ANSWER = "CHECK_ANSWER";
export const SET_CURSOR_INDEX = "SET_CURSOR_INDEX";

export const CHANGE_DEMO_TIMESTAMP = "CHANGE_DEMO_TIMESTAMP";
export const CHANGE_DEMO_DAILYCOUNT = "CHANGE_DEMO_DAILYCOUNT";
